import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("chat", "routes/chat.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("profile", "routes/profile.tsx"),
  route("api/chat", "routes/api.chat.ts"),
  route("api/sources", "routes/api.sources.ts"),
  route("api/auth/signup", "routes/api.auth.signup.ts"),
  route("api/auth/login", "routes/api.auth.login.ts"),
  route("api/auth/logout", "routes/api.auth.logout.ts"),
  route("api/auth/refresh", "routes/api.auth.refresh.ts"),
  route("api/auth/forgot-password", "routes/api.auth.forgot-password.ts"),
  route("api/auth/reset-password", "routes/api.auth.reset-password.ts"),
  route("api/auth/google", "routes/api.auth.google.ts"),
  route("api/auth/google/callback", "routes/api.auth.google.callback.ts"),
  route("api/auth/apple", "routes/api.auth.apple.ts"),
  route("api/auth/apple/callback", "routes/api.auth.apple.callback.ts"),
  route("api/profile", "routes/api.profile.ts"),
  route("api/conversations", "routes/api.conversations.ts"),
  route("api/conversations/:id", "routes/api.conversations.$id.ts"),
  route("api/conversations/:id/title", "routes/api.conversations.$id.title.ts"),
  route("pricing", "routes/pricing.tsx"),
  route("offline", "routes/offline.tsx"),
  route("api/stripe/checkout", "routes/api.stripe.checkout.ts"),
  route("api/stripe/portal", "routes/api.stripe.portal.ts"),
  route("api/stripe/webhook", "routes/api.stripe.webhook.ts"),
  route("api/cron/trial-reminders", "routes/api.cron.trial-reminders.ts"),
  route("api/feedback", "routes/api.feedback.ts"),
  route("api/conversations/:id/share", "routes/api.conversations.$id.share.ts"),
  route("share/:token", "routes/share.$token.tsx"),
  route("admin", "routes/admin.tsx"),
  route("api/admin/custom-texts", "routes/api.admin.custom-texts.ts"),
] satisfies RouteConfig;
